"""CONSTANTS"""

"""
FILE CONSTANTS
"""
SOURCE_DATA_TXT = 'SOURCEDATA.txt'
SOURCE_DATA_COLUMNS_TXT = 'SOURCECOLUMNS.txt'
CSV_EXTENSION = '.csv'
SOURCE_DATA_PROCESSED = 'SOURCE_DATA_PROCESSED'

# DELIMITERS
DEFAULT_DELIMITER = '|'
COMMA = ','

# TIMESTAMP FORMATS
FILE_NAME_TIMESTAMP_FORMAT = '%Y-%m-%dT%H:%M:%S'
